version: "3.7"
services:

  mongo:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: caronte
      MONGO_INITDB_ROOT_PASSWORD: you-should-change-this-password
      MONGO_INITDB_DATABASE: caronte
    network_mode: host
    restart: unless-stopped
    command: mongod --bind_ip 127.0.0.1

  caronte:
    build: .
    environment:
      MONGO_HOST: 127.0.0.1
      MONGO_PORT: 27017
      DB_USERNAME: caronte
      DB_PASSWORD: you-should-change-this-password
    depends_on:
      - mongo
    network_mode: host
    restart: unless-stopped
    cap_add:
      - CAP_NET_ADMIN
      - CAP_NET_RAW
